// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'gym_location_full.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'gym_location_full.g.dart';

@freezed
class GymLocationFull with _$GymLocationFull {
  const factory GymLocationFull({
    String? locality,
    String? state,
    String? state_code,
    String? country,
    String? country_code,
    String? raw,
  }) = _GymLocationFull;

  factory GymLocationFull.fromJson(Map<String, Object?> json) => _$GymLocationFullFromJson(json);
}
